variables:
  PROJECT_VERSION: "1.0"
  PROJECT_NAME: "fakedeals"
  PROJECT_IMAGE_NAME: ""
  PROJECT_BLOCK_ON_SECURITY_ISSUES: "false"
  PROJECT_LANGUAGES: "java"
  PROJECT_BUILD_IMAGE: "maven:3-openjdk-11"
  PROJECT_BUILD_SCRIPT: "maven clean install"
  PROJECT_BUILD_LIBS: ""
  PROJECT_BUILD_ARTIFACTS: "~/.m2/repository"
  FORTIFY_SSC_URL: "http://ssc:8080/"
  FORTIFY_ATTRIBUTES: ""
  FORTIFY_ISSUE_TEMPLATE: "SOGETI Issue Template"
  SAST_ENABLE: "true"
  SAST_EXCLUDES: ""
  SAST_FORTIFY_JVM_OPTIONS: "-Xmx4G"
  SAST_FORTIFY_TOUCHLESS_COMMAND: "mvn"
  SAST_FORTIFY_HLA: "true"
  SAST_FORTIFY_JAVA_VERSION: "11"
  SAST_FORTIFY_PHP_VERSION: ""
  SAST_FORTIFY_PYTHON_VERSION: ""
  SAST_FORTIFY_PASS_FAIL_POLICY: "[fortify priority order]:medium AND [analysis type]:SCA"
  # full, partial or no
  SAST_FORTIFY_SCANCENTRAL_ENABLE: "no"
  SAST_FORTIFY_SCANCENTRAL_CONTROLLER_URL: ""
  SAST_FORTIFY_SCANCENTRAL_BUILD_TOOL: ""
  SAST_FORTIFY_SCANCENTRAL_BUILD_FILE: ""
  SAST_FORTIFY_SCANCENTRAL_WAIT_FOR_SCAN_COMPLETE: ""
  SAST_FORTIFY_SCANCENTRAL_POOL: ""
  OSS_ODC_ENABLE: "true"
  OSS_ODC_EXCLUDES: ""
  OSS_ODC_PASS_FAIL_POLICY: "[fortify priority order]:critical AND [analysis type]:OWASP_DEPCHECK"
  OSS_ODT_ENABLE: "false"
  OSS_ODT_DEPENDENCY_MANAGER: "npm"
  OSS_ODT_URL: "https://otrackapi.agile4security.io/"
  OSS_ODT_PASS_FAIL_POLICY: ""
  OSS_NEXUS_IQ_ENABLE: "true"
  OSS_NEXUS_IQ_STAGE: "release"
  OSS_NEXUS_IQ_EXCLUDES: ""
  OSS_NEXUS_IQ_URL: "http://nexus-iq-server:8070/"
  OSS_NEXUS_IQ_PASS_FAIL_POLICY: "[fortify priority order]:medium AND [analysis type]:SONATYPE"
  CQ_SONARQUBE_ENABLE: ""
  CQ_SONARQUBE_URL: ""
  CQ_SONARQUBE_PASS_FAIL_POLICY: ""
  CIST_TRIVY_ENABLE: "false"
  CIST_TRIVY_PASS_FAIL_POLICY: ""
  DAST_ACUNETIX_ENABLE: "false"
  DAST_ACUNETIX_URL: "https://daster:3443/"
  DAST_ACUNETIX_SCAN_TYPE: "default"
  DAST_ACUNETIX_WAIT_FOR_SCAN_COMPLETE: "true"
  DAST_ACUNETIX_TARGET_ADDRESS: "https://ssc.agile4security.io/"
  DAST_ACUNETIX_TARGET_DESCRIPTION: "SSC platform Test"
  DAST_ACUNETIX_TARGET_CRITICALITY: "10"
  DAST_ACUNETIX_PASS_FAIL_POLICY: ""

include:
  - project: "fmolina/gitlabcicd-secgates"
    ref: master
    file: ".gitlab-ci-base.yml"
